/* AUTO-GENERATED by tools/import_photos.py — do not hand-edit */
window.SSP_GALLERY = {
 "categories": [
  {
   "id": "water-heaters",
   "name": "Water Heaters"
  },
  {
   "id": "showers",
   "name": "Showers & Tubs"
  },
  {
   "id": "kitchens-fixtures",
   "name": "Kitchens & Fixtures"
  },
  {
   "id": "repipe-roughin",
   "name": "Repipes & Rough-In"
  },
  {
   "id": "commercial",
   "name": "Commercial"
  },
  {
   "id": "finished-baths",
   "name": "Finished Bathrooms"
  }
 ],
 "photos": [
  {
   "id": "IMG_0434",
   "cat": "water-heaters",
   "catName": "Water Heaters",
   "caption": "Tankless water heater install with gas and water manifold"
  },
  {
   "id": "IMG_1226",
   "cat": "water-heaters",
   "catName": "Water Heaters",
   "caption": "Wall-mounted heater with copper manifold and shut-offs"
  },
  {
   "id": "IMG_1538",
   "cat": "water-heaters",
   "catName": "Water Heaters",
   "caption": "Exterior tankless install with gas line and shut-off"
  },
  {
   "id": "IMG_6179",
   "cat": "water-heaters",
   "catName": "Water Heaters",
   "caption": "Tankless heater, copper manifold, isolation valves"
  },
  {
   "id": "AC9FEC66-C6E3-4C0D-B2A0-052F9FFD571C",
   "cat": "showers",
   "catName": "Showers & Tubs",
   "caption": "Shower system: rain head, handheld and valve trim"
  },
  {
   "id": "IMG_1233",
   "cat": "showers",
   "catName": "Showers & Tubs",
   "caption": "Rain head, handheld and thermostatic trim"
  },
  {
   "id": "IMG_4563",
   "cat": "showers",
   "catName": "Showers & Tubs",
   "caption": "Shower valve trim and handheld on tile"
  },
  {
   "id": "IMG_6377",
   "cat": "showers",
   "catName": "Showers & Tubs",
   "caption": "Marble shower with rain head, handheld and niche"
  },
  {
   "id": "IMG_6379",
   "cat": "showers",
   "catName": "Showers & Tubs",
   "caption": "Freestanding tub and shower with matte black trim"
  },
  {
   "id": "IMG_8953",
   "cat": "showers",
   "catName": "Showers & Tubs",
   "caption": "Freestanding tub with floor-mount filler"
  },
  {
   "id": "IMG_8954",
   "cat": "showers",
   "catName": "Showers & Tubs",
   "caption": "Tub and shower with black fixtures"
  },
  {
   "id": "IMG_1236",
   "cat": "showers",
   "catName": "Showers & Tubs",
   "caption": "Freestanding tub with floor-mount tub filler"
  },
  {
   "id": "57DCEFC5-D294-40BE-95F5-50290FC526C2",
   "cat": "kitchens-fixtures",
   "catName": "Kitchens & Fixtures",
   "caption": "Pot filler over a gas range"
  },
  {
   "id": "IMG_0955",
   "cat": "kitchens-fixtures",
   "catName": "Kitchens & Fixtures",
   "caption": "Kitchen sink and faucet"
  },
  {
   "id": "IMG_1227",
   "cat": "kitchens-fixtures",
   "catName": "Kitchens & Fixtures",
   "caption": "Apron-front sink with bridge faucet"
  },
  {
   "id": "IMG_1228",
   "cat": "kitchens-fixtures",
   "catName": "Kitchens & Fixtures",
   "caption": "Wall-mounted pot filler"
  },
  {
   "id": "IMG_1229",
   "cat": "kitchens-fixtures",
   "catName": "Kitchens & Fixtures",
   "caption": "Vessel sink and faucet on a wood vanity"
  },
  {
   "id": "IMG_1377",
   "cat": "kitchens-fixtures",
   "catName": "Kitchens & Fixtures",
   "caption": "Double vanity with undermount sinks and faucets"
  },
  {
   "id": "IMG_5610",
   "cat": "kitchens-fixtures",
   "catName": "Kitchens & Fixtures",
   "caption": "Farmhouse sink with gooseneck faucet"
  },
  {
   "id": "IMG_3448",
   "cat": "repipe-roughin",
   "catName": "Repipes & Rough-In",
   "caption": "Water lines roughed into framed walls"
  },
  {
   "id": "IMG_3670",
   "cat": "repipe-roughin",
   "catName": "Repipes & Rough-In",
   "caption": "Overhead pipe runs"
  },
  {
   "id": "IMG_4902",
   "cat": "repipe-roughin",
   "catName": "Repipes & Rough-In",
   "caption": "PEX manifold and distribution under floor joists"
  },
  {
   "id": "IMG_6393",
   "cat": "repipe-roughin",
   "catName": "Repipes & Rough-In",
   "caption": "Drain, vent and water lines roughed in"
  },
  {
   "id": "IMG_6420",
   "cat": "repipe-roughin",
   "catName": "Repipes & Rough-In",
   "caption": "Copper manifold and distribution"
  },
  {
   "id": "IMG_8023",
   "cat": "repipe-roughin",
   "catName": "Repipes & Rough-In",
   "caption": "Rough-in through framing"
  },
  {
   "id": "IMG_2492",
   "cat": "commercial",
   "catName": "Commercial",
   "caption": "Overhead commercial pipe and conduit runs"
  },
  {
   "id": "IMG_2493",
   "cat": "commercial",
   "catName": "Commercial",
   "caption": "Commercial overhead piping grid"
  },
  {
   "id": "IMG_8775",
   "cat": "commercial",
   "catName": "Commercial",
   "caption": "Commercial wall-mount lavatory"
  },
  {
   "id": "IMG_8776",
   "cat": "commercial",
   "catName": "Commercial",
   "caption": "ADA-height toilet with grab bar"
  },
  {
   "id": "IMG_8779",
   "cat": "commercial",
   "catName": "Commercial",
   "caption": "Commercial urinal install"
  },
  {
   "id": "IMG_2459",
   "cat": "finished-baths",
   "catName": "Finished Bathrooms",
   "caption": "Finished bath with glass shower and vanity"
  },
  {
   "id": "IMG_0425",
   "cat": "finished-baths",
   "catName": "Finished Bathrooms",
   "caption": "Finished master bath"
  }
 ]
};
window.SSP_PHOTO_ALT = {
 "img/photos/water-heaters.jpg": "Tankless heater, copper manifold, isolation valves",
 "img/photos/shower-valves.jpg": "Marble shower with rain head, handheld and niche",
 "img/photos/fixtures.jpg": "Farmhouse sink with gooseneck faucet",
 "img/photos/repipe.jpg": "PEX manifold and distribution under floor joists",
 "img/photos/drains.jpg": "Drain, vent and water lines roughed in"
};
